# This workflow will do a clean installation of node dependencies, build the source code and run tests with node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push]

jobs:
  build-client:
    concurrency: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 8.x
        uses: actions/setup-node@v3
        with:
          node-version: '8.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
